spring.application.name=management

# OLTP Database (Primary)
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS01;databaseName=Medical;encrypt=false
spring.datasource.username=sa
spring.datasource.password=5432167890
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# DW Database (Data Warehouse)
spring.dw-datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS01;databaseName=MedicalDW;encrypt=false
spring.dw-datasource.username=sa
spring.dw-datasource.password=5432167890
spring.dw-datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
